[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets']

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
hook_source = '''
  let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_event = 'TextYankPost'
on_source = ['denite.nvim']

[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
depends = ['neomru.vim']
hook_add = '''
nmap <silent> <C-u><C-q> :<C-u>Denite directory_rec<CR>
nmap <silent> <C-u><C-w> :<C-u>Denite line<CR>
nmap <silent> <C-u><C-e> :<C-u>Denite grep<CR>
nmap <silent> <C-u><C-r> :<C-u>DeniteCursorWord grep<CR>
nmap <silent> <C-u><C-t> :<C-u>Denite file_mru<CR>
nmap <silent> <C-u><C-y> :<C-u>Denite neoyank<CR>
nmap <silent> <C-u><C-u> :<C-u>Denite file_rec<CR>
'''

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'neomake/neomake'
on_ft = ['python']
hook_source = '''
  autocmd! BufEnter,BufWritePost * Neomake
  let g:neomake_python_enabled_makers = ['python', 'flake8']
'''

[[plugins]]
repo = 'zchee/deoplete-jedi'
depends = ['deoplete.nvim']
on_ft = ['python']
on_i = 1

[[plugins]]
repo = 'zchee/deoplete-zsh'
on_ft = ['zsh', 'sh']

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = ['python']

[[plugins]]
repo = 'kannokanno/previm'
hook_source = '''
  let g:previm_open_cmd = 'open -a "Google Chrome"'
'''
